---
# tasks file for aquatone

# This tool is installed a bit differently.  The release zip for it
# contains pre-compiled Go code, which is what we want to install.
- name: Install aquatone
  block:
    - name: Install dependencies for aquatone
      package:
        name:
          - chromium
          - unzip
    - name: Create a directory where aquatone will be installed manually
      file:
        group: "{{ group }}"
        # Allow both root and the desired group to have full
        # permissions in these directories
        mode: 0775
        path: /tools/{{ item.dir_name }}
        state: directory
      loop:
        - "{{ aquatone }}"
      loop_control:
        label: "{{ item.dir_name }}"
    - name: Manually install aquatone
      unarchive:
        dest: "/tools/{{ item.dir_name }}"
        group: "{{ group }}"
        remote_src: yes
        src: "{{ item.repo }}"
      loop:
        - "{{ aquatone }}"
      loop_control:
        label: "{{ item.repo }}"
